import Foundation
import Combine
import AppKit

public enum CleanActionType: Equatable, Sendable {
    case path(URL, deleteEntireFolder: Bool)
    case command(scan: String, clean: String)
    case complex(paths: [URL], userClean: String, adminClean: String)
}

public struct JunkCategory: Identifiable, Sendable {
    public let id = UUID()
    public let name: String
    public let description: String
    public var size: Int64 = 0
    public var count: Int = 0
    public var isSelected: Bool
    public let needsAdmin: Bool
    public let actionType: CleanActionType
    
    public var displayValue: String? {
        if case .command = actionType {
            return count > 0 ? "\(count) item(s)" : "None"
        }
        return nil
    }
}

@MainActor
public class DeepCleanViewModel: ObservableObject {
    @Published public var categories: [JunkCategory] = []
    @Published public var isScanning: Bool = false
    @Published public var isCleaning: Bool = false
    @Published public var errorMessage: String? = nil
    
    public var totalSelectedSize: Int64 {
        categories.filter { $0.isSelected }.reduce(0) { $0 + $1.size }
    }
    
    public var hasSelectedItems: Bool {
        categories.contains { $0.isSelected && ($0.size > 0 || $0.count > 0) }
    }
    
    public init() {
        setupCategories()
    }
    
    private func setupCategories() {
        let fileManager = FileManager.default
        let homeDir = fileManager.homeDirectoryForCurrentUser
        
        var initialCategories: [JunkCategory] = [
            JunkCategory(name: "User Caches", description: "Temporary application data. Safe to delete.", isSelected: true, needsAdmin: false, actionType: .path(homeDir.appendingPathComponent("Library/Caches"), deleteEntireFolder: false)),
            JunkCategory(name: "System Logs", description: "Log files generated by macOS and apps.", isSelected: true, needsAdmin: false, actionType: .path(homeDir.appendingPathComponent("Library/Logs"), deleteEntireFolder: false)),
            JunkCategory(name: "Trash", description: "Files you've moved to the Trash.", isSelected: true, needsAdmin: false, actionType: .path(homeDir.appendingPathComponent(".Trash"), deleteEntireFolder: false))
        ]
        
        // 1. macOS Install staging leftovers
        if !isUpdateInProgress() {
            let updateBundle = URL(fileURLWithPath: "/System/Volumes/Data/macOS Install Data/UpdateBundle")
            initialCategories.append(JunkCategory(name: "macOS Update Staging", description: "Leftover files from macOS updates.", isSelected: false, needsAdmin: true, actionType: .path(updateBundle, deleteEntireFolder: true)))
        }
        
        // 2. Xcode Caches
        let xcodeUserCache = homeDir.appendingPathComponent("Library/Caches/com.apple.dt.Xcode")
        if fileManager.fileExists(atPath: xcodeUserCache.path) {
            initialCategories.append(JunkCategory(name: "Xcode User Cache", description: "Xcode application cache.", isSelected: false, needsAdmin: false, actionType: .path(xcodeUserCache, deleteEntireFolder: false)))
        }
        
        let xcodeSystemCache = URL(fileURLWithPath: "/Library/Caches/com.apple.dt.Xcode")
        if fileManager.fileExists(atPath: xcodeSystemCache.path) {
            initialCategories.append(JunkCategory(name: "Xcode System Cache", description: "Xcode system-wide cache.", isSelected: false, needsAdmin: true, actionType: .path(xcodeSystemCache, deleteEntireFolder: true)))
        }
        
        // 2. Xcode DerivedData
        let derivedData = homeDir.appendingPathComponent("Library/Developer/Xcode/DerivedData")
        if fileManager.fileExists(atPath: derivedData.path) {
            initialCategories.append(JunkCategory(name: "Xcode Derived Data", description: "Intermediate build results. Safe to delete.", isSelected: false, needsAdmin: false, actionType: .path(derivedData, deleteEntireFolder: false)))
        }
        
        // 3. Xcode Archives
        let xcodeArchives = homeDir.appendingPathComponent("Library/Developer/Xcode/Archives")
        if fileManager.fileExists(atPath: xcodeArchives.path) {
            initialCategories.append(JunkCategory(name: "Xcode Archives", description: "Your app export history. Safe to delete, but review if needed.", isSelected: false, needsAdmin: false, actionType: .path(xcodeArchives, deleteEntireFolder: false)))
        }
        
        // 4. iOS Device Support
        let deviceSupport = homeDir.appendingPathComponent("Library/Developer/Xcode/iOS DeviceSupport")
        if fileManager.fileExists(atPath: deviceSupport.path) {
            initialCategories.append(JunkCategory(name: "iOS Device Support", description: "Support files for old OS versions.", isSelected: false, needsAdmin: false, actionType: .path(deviceSupport, deleteEntireFolder: false)))
        }
        
        // 5. Unavailable iOS Simulators
        if runShellCommand("command -v xcrun").trimmingCharacters(in: .whitespacesAndNewlines) != "" {
            initialCategories.append(JunkCategory(name: "Unavailable Simulators", description: "Old simulator devices no longer available.", isSelected: false, needsAdmin: false, actionType: .command(scan: "xcrun simctl list devices unavailable 2>/dev/null | grep -c 'unavailable'", clean: "xcrun simctl delete unavailable")))
        }
        
        // 6. Diagnostic reports
        let diagnosticReports = homeDir.appendingPathComponent("Library/Logs/DiagnosticReports")
        if fileManager.fileExists(atPath: diagnosticReports.path) {
            initialCategories.append(JunkCategory(name: "Diagnostic Reports", description: "Crash logs and system diagnostics.", isSelected: false, needsAdmin: false, actionType: .path(diagnosticReports, deleteEntireFolder: true)))
        }
        
        // 7. Local Time Machine snapshots
        if runShellCommand("command -v tmutil").trimmingCharacters(in: .whitespacesAndNewlines) != "" {
            initialCategories.append(JunkCategory(name: "Local Time Machine Snapshots", description: "Local snapshots created during updates.", isSelected: false, needsAdmin: true, actionType: .command(scan: "tmutil listlocalsnapshots / 2>/dev/null | grep -c 'com.apple.TimeMachine'", clean: "tmutil listlocalsnapshots / 2>/dev/null | grep 'com.apple.TimeMachine' | while read -r snap; do sudo tmutil deletelocalsnapshots \"${snap##*.}\" 2>/dev/null; done")))
        }
        
        // 8. Spotlight and Knowledge Caches
        let spotlightUserClean = "rm -rf '\(homeDir.path)/Library/Metadata/CoreSpotlight'; rm -rf '\(homeDir.path)/Library/Application Support/Knowledge'/knowledgeC.db*"
        let spotlightAdminClean = "killall mds mds_stores 2>/dev/null; mdutil -E /."
        let spotlightPaths = [
            homeDir.appendingPathComponent("Library/Metadata/CoreSpotlight"),
            homeDir.appendingPathComponent("Library/Application Support/Knowledge/knowledgeC.db"),
            homeDir.appendingPathComponent("Library/Application Support/Knowledge/knowledgeC.db-shm"),
            homeDir.appendingPathComponent("Library/Application Support/Knowledge/knowledgeC.db-wal")
        ]
        
        initialCategories.append(JunkCategory(
            name: "Spotlight & Knowledge Caches",
            description: "Clears Spotlight search index and Siri Knowledge databases to fix search issues or free up space.",
            isSelected: false,
            needsAdmin: true,
            actionType: .complex(paths: spotlightPaths, userClean: spotlightUserClean, adminClean: spotlightAdminClean)
        ))
        
        categories = initialCategories
    }
    
    private func isUpdateInProgress() -> Bool {
        let softwareUpdated = runShellCommand("pgrep -x softwareupdated")
        let installMonitor = runShellCommand("ps aux | grep '[i]nstall_monitor'")
        return !softwareUpdated.isEmpty && !installMonitor.isEmpty
    }
    
    private nonisolated func runShellCommand(_ command: String) -> String {
        let task = Process()
        let pipe = Pipe()
        task.standardOutput = pipe
        task.standardError = pipe
        task.arguments = ["-c", command]
        task.launchPath = "/bin/bash"
        task.standardInput = nil
        try? task.run()
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        return String(data: data, encoding: .utf8) ?? ""
    }
    
    public func scan() async {
        isScanning = true
        
        var updatedCategories = categories
        for i in 0..<updatedCategories.count {
            let category = updatedCategories[i]
            switch category.actionType {
            case .path(let url, _):
                let size = await calculateSize(of: url)
                updatedCategories[i].size = size
            case .command(let scanCommand, _):
                let output = await Task.detached { self.runShellCommand(scanCommand) }.value
                if let count = Int(output.trimmingCharacters(in: .whitespacesAndNewlines)) {
                    updatedCategories[i].count = count
                }
            case .complex(let paths, _, _):
                var totalSize: Int64 = 0
                for path in paths {
                    totalSize += await calculateSize(of: path)
                }
                updatedCategories[i].size = totalSize
            }
        }
        
        self.categories = updatedCategories
        self.isScanning = false
    }
    
    public func clean() async {
        isCleaning = true
        errorMessage = nil
        
        let selectedCategories = categories.filter { $0.isSelected }
        
        let resultError = await Task.detached {
            let fileManager = FileManager.default
            var adminPathsToDelete: [String] = []
            var adminCommandsToRun: [String] = []
            var resultingErrorMessage: String? = nil
            
            for category in selectedCategories {
                switch category.actionType {
                case .path(let path, let deleteEntireFolder):
                    if category.needsAdmin {
                        adminPathsToDelete.append(path.path)
                    } else {
                        do {
                            if deleteEntireFolder {
                                try fileManager.removeItem(at: path)
                            } else {
                                let contents = try fileManager.contentsOfDirectory(at: path, includingPropertiesForKeys: nil)
                                for item in contents {
                                    try? fileManager.removeItem(at: item)
                                }
                            }
                        } catch {
                            print("Error cleaning \(category.name): \(error)")
                            resultingErrorMessage = "Failed to clean \(category.name): \(error.localizedDescription)"
                        }
                    }
                case .command(_, let cleanCommand):
                    if category.needsAdmin {
                        adminCommandsToRun.append(cleanCommand)
                    } else {
                        _ = self.runShellCommand(cleanCommand)
                    }
                case .complex(_, let userClean, let adminClean):
                    _ = self.runShellCommand(userClean)
                    if category.needsAdmin {
                        adminCommandsToRun.append(adminClean)
                    } else {
                        _ = self.runShellCommand(adminClean)
                    }
                }
            }
            
            // Execute admin batch commands using AppleScript
            if !adminPathsToDelete.isEmpty || !adminCommandsToRun.isEmpty {
                var scriptCommands: [String] = []
                
                for path in adminPathsToDelete {
                    let safePath = path.replacingOccurrences(of: "'", with: "'\\''")
                    scriptCommands.append("rm -rf '\(safePath)'")
                }
                
                for command in adminCommandsToRun {
                    // If the bash command itself uses sudo, we can just run it without sudo in the AppleScript since AppleScript executes as root
                    let cleanCommand = command.replacingOccurrences(of: "sudo ", with: "")
                    scriptCommands.append(cleanCommand)
                }
                
                let combinedCommand = scriptCommands.joined(separator: "; ")
                let safeCombinedCommand = combinedCommand.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
                
                let scriptSource = """
                do shell script "\(safeCombinedCommand)" with administrator privileges
                """
                
                if let script = NSAppleScript(source: scriptSource) {
                    var errorInfo: NSDictionary?
                    script.executeAndReturnError(&errorInfo)
                    if let errorInfo = errorInfo {
                        let msg = errorInfo[NSAppleScript.errorMessage] as? String ?? "Unknown error"
                        print("AppleScript admin delete failed: \(msg)")
                        if msg.contains("Operation not permitted") {
                            resultingErrorMessage = "Some files could not be deleted because they are protected by macOS System Integrity Protection (SIP)."
                        } else {
                            resultingErrorMessage = "Administrator deletion failed: \(msg)"
                        }
                    }
                }
            }
            
            return resultingErrorMessage
        }.value
        
        if let error = resultError {
            self.errorMessage = error
        }
        
        await scan()
        isCleaning = false
    }
    
    public func toggleSelection(id: UUID) {
        if let index = categories.firstIndex(where: { $0.id == id }) {
            categories[index].isSelected.toggle()
        }
    }
    
    private func calculateSize(of url: URL) async -> Int64 {
        return await Task.detached {
            var totalSize: Int64 = 0
            let fileManager = FileManager.default
            if let enumerator = fileManager.enumerator(at: url, includingPropertiesForKeys: [.totalFileAllocatedSizeKey, .fileSizeKey], options: []) {
                while let obj = enumerator.nextObject() {
                    if let fileURL = obj as? URL,
                       let resources = try? fileURL.resourceValues(forKeys: [.totalFileAllocatedSizeKey, .fileSizeKey]) {
                        if let allocated = resources.totalFileAllocatedSize, allocated > 0 {
                            totalSize += Int64(allocated)
                        } else if let size = resources.fileSize {
                            totalSize += Int64(size)
                        }
                    }
                }
            }
            return totalSize
        }.value
    }
}
