import Foundation
import Combine

public struct JunkCategory: Identifiable {
    public let id = UUID()
    public let name: String
    public let description: String
    public let path: URL
    public var size: Int64
    public var isSelected: Bool
}

@MainActor
public class DeepCleanViewModel: ObservableObject {
    @Published public var categories: [JunkCategory] = []
    @Published public var isScanning: Bool = false
    @Published public var isCleaning: Bool = false
    
    public var totalSelectedSize: Int64 {
        categories.filter { $0.isSelected }.reduce(0) { $0 + $1.size }
    }
    
    public init() {
        setupCategories()
    }
    
    private func setupCategories() {
        let fileManager = FileManager.default
        let homeDir = fileManager.homeDirectoryForCurrentUser
        
        categories = [
            JunkCategory(name: "User Caches", description: "Temporary application data. Safe to delete.", path: homeDir.appendingPathComponent("Library/Caches"), size: 0, isSelected: true),
            JunkCategory(name: "System Logs", description: "Log files generated by macOS and apps.", path: homeDir.appendingPathComponent("Library/Logs"), size: 0, isSelected: true),
            JunkCategory(name: "Trash", description: "Files you've moved to the Trash.", path: homeDir.appendingPathComponent(".Trash"), size: 0, isSelected: true)
        ]
        
        let derivedData = homeDir.appendingPathComponent("Library/Developer/Xcode/DerivedData")
        if fileManager.fileExists(atPath: derivedData.path) {
            categories.append(JunkCategory(name: "Xcode Derived Data", description: "Intermediate build results. Safe to delete.", path: derivedData, size: 0, isSelected: false))
        }
    }
    
    public func scan() async {
        isScanning = true
        
        var updatedCategories = categories
        for i in 0..<updatedCategories.count {
            let path = updatedCategories[i].path
            let size = await calculateSize(of: path)
            updatedCategories[i].size = size
        }
        
        self.categories = updatedCategories
        self.isScanning = false
    }
    
    public func clean() async {
        isCleaning = true
        let fileManager = FileManager.default
        
        for category in categories where category.isSelected {
            do {
                let contents = try fileManager.contentsOfDirectory(at: category.path, includingPropertiesForKeys: nil)
                for item in contents {
                    try? fileManager.removeItem(at: item)
                }
            } catch {
                print("Error cleaning \(category.name): \(error)")
            }
        }
        
        await scan()
        isCleaning = false
    }
    
    public func toggleSelection(id: UUID) {
        if let index = categories.firstIndex(where: { $0.id == id }) {
            categories[index].isSelected.toggle()
        }
    }
    
    private func calculateSize(of url: URL) async -> Int64 {
        return await Task.detached {
            var totalSize: Int64 = 0
            let fileManager = FileManager.default
            if let enumerator = fileManager.enumerator(at: url, includingPropertiesForKeys: [.totalFileAllocatedSizeKey, .fileSizeKey], options: []) {
                while let obj = enumerator.nextObject() {
                    if let fileURL = obj as? URL,
                       let resources = try? fileURL.resourceValues(forKeys: [.totalFileAllocatedSizeKey, .fileSizeKey]) {
                        if let allocated = resources.totalFileAllocatedSize, allocated > 0 {
                            totalSize += Int64(allocated)
                        } else if let size = resources.fileSize {
                            totalSize += Int64(size)
                        }
                    }
                }
            }
            return totalSize
        }.value
    }
}
